[env]
NVIM_LEVEL = "x"
NVIM_LIGHT = "0"
TERM = "alacritty"

[font]
size = 11

[font.normal]
family = "Lilex"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
startup_mode = "Maximized"

[terminal.shell]
program = "nu"

