[env]
TERM = "alacritty"

[font]
size = 10.5

[font.normal]
family = "Lilex"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
#startup_mode = "Maximized"
dimensions = { columns = 120, lines = 40 }

[terminal.shell]
program = "nu"
