# theme = "gruvbox_light"
# theme = "zenburn"
theme = 'gruvbox_dark_soft'

[editor]
line-number = "relative"
middle-click-paste = true
mouse = true
enable-steel = true
trim-trailing-whitespace = true
trim-final-newlines	= true
popup-border = "none"
commandline = false

[editor.auto-save]
focus-lost = true
idle = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.insert]
"A-;" = "normal_mode"

[keys.normal]
"A-j" = "page_cursor_half_down"
"A-k" = "page_cursor_half_up"

"A-s" = "save_selection"
"C-s" = "split_selection_on_newline"

"A-h" = "jump_backward"
"A-l" = "jump_forward"

[keys.normal.space]
space = "goto_word"
o = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.select]
space = { space = "goto_word" }
"A-;" = "normal_mode"
"A-'" = "flip_selections"
"A-j" = "page_cursor_half_down"
"A-k" = "page_cursor_half_up"
