#theme = "gruvbox_light"
theme = "zenburn"
#theme = "everforest_dark"

[editor]
line-number = "relative"
middle-click-paste = true
mouse = true
enable-steel = true
trim-trailing-whitespace = false
trim-final-newlines	= false
popup-border = "none"

[editor.auto-save]
focus-lost = true
idle = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
merge-with-commandline = true

[keys.insert]
"A-;" = "normal_mode"

[keys.normal]
"A-j" = "page_cursor_half_down"
"A-k" = "page_cursor_half_up"
space = { space = "goto_word" }

"A-s" = "save_selection"
"C-s" = "split_selection_on_newline"

"A-h" = "jump_backward"
"A-l" = "jump_forward"

[keys.select]
space = { space = "goto_word" }
"A-;" = "normal_mode"
"A-'" = "flip_selections"
"A-j" = "page_cursor_half_down"
"A-k" = "page_cursor_half_up"
